### ISSUE TITLE
Did you use 3d deconve head or 2d deconv head in DSD module?

### ISSUE THREAD

**Issue by shyanguan** [JDAI-CV/DSD-SATN#9]
Hi @Arthur151, very fancy idea, and nice work! Here I want to check a detail in your paper and hope you can help me. 

In your paper, you mentioned that DIR includes 2d/3d joint conversion. But in your code, there seems only is 2d deconv head is used. Am I right?

**Comment by Arthur151** [comment]
Thanks for your interests! We have tried both 2D and 3D "deconv head" in experiments. 2D joints provides better generalization ability, while the 3D joints improve the performance. In this  repository, only 2D "deconv head" is used.

**Comment by shyanguan** [comment]
Okay, and for some datasets which has no 3d joints as ground-truth, will you use reprojected joint loss or just ignore this kind of data?

**Comment by Arthur151** [comment]
Using the reprojected joint loss.------------------ Original ------------------From: sysysys  <notifications@github.com>Date: 周一,8月 10,2020 2:38 下午To: JDAI-CV/DSD-SATN <DSD-SATN@noreply.github.com>Cc: Yu Sun <yusun@stu.hit.edu.cn>, Mention <mention@noreply.github.com>Subject: Re: [JDAI-CV/DSD-SATN] Did you use 3d deconve head or 2d deconv headin DSD module? (#9)
Okay, and for some datasets which has no 3d joints as ground-truth, will you use reprojected joint loss or just ignore this kind of data?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JDAI-CV/DSD-SATN/issues/9#issuecomment-671188433",
"url": "https://github.com/JDAI-CV/DSD-SATN/issues/9#issuecomment-671188433",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shyanguan** [comment]
Thanks for your kindly reply! Thank you very much!
